version: '3'
services:
  web:
    build:
      context: ./app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./app/static:/app/static
      - ./app/media:/app/media
      - ./nginx/data:/usr/share/nginx/data
    ports:
      - "80:80"
